#!/bin/sh
# Sandbox entry point for the DSH Android app.
#
# Runs inside the PRoot guest. Starts the two long-lived services the app's Web
# UI needs and then becomes the harness, so the app has exactly one process to
# supervise (and --kill-on-exit takes the rest down with it):
#
#   android-pty    node-pty shell endpoint on 127.0.0.1:$DSH_PTY_PORT, so the
#                  Web UI can offer a terminal without an active session
#   dsh web        the harness itself on 127.0.0.1:$DSH_PORT
#
# Both tokens are generated by the app and passed in the environment, because
# the Web UI (the only client) has to be told them through the native bridge.
set -eu

DSH_PORT="${DSH_PORT:-3080}"
DSH_PTY_PORT="${DSH_PTY_PORT:-3099}"
DSH_HOME="${HOME:-/root}"
DSH_INSTALL="${DSH_INSTALL:-/opt/dsh}"

# Node lives in different places per distribution (distro package: /usr/bin,
# official tarball or nvm: /usr/local/bin). Resolve it once so the same payload
# script works on any rootfs the user boots.
NODE="$(command -v node || true)"
[ -x "$NODE" ] || NODE=""
for candidate in /usr/local/bin/node /usr/bin/node; do
  [ -n "$NODE" ] && break
  [ -x "$candidate" ] && NODE="$candidate"
done
if [ -z "$NODE" ]; then
  echo "start-dsh: no node found in PATH ($PATH)"
  exit 4
fi
echo "start-dsh: node=$NODE"

# Repair an already-installed sandbox on the way up. The rootfs cannot be written
# by a hot package, so a fix to a file inside it has to be applied from here at
# boot; the script is idempotent and prints only when it changes something.
# See payload/opt/dsh/android/repair-dsh.mjs for what it fixes.
"$NODE" "$DSH_INSTALL/android/repair-dsh.mjs" "$DSH_INSTALL/node_modules" 2>&1 | sed 's/^/start-dsh: /' || true


mkdir -p "$DSH_HOME/.dsh"

# First run in a fresh home: seed the preinstalled profile (the app's plugin
# rows) from the immutable payload copy, so user edits afterwards persist.
# $HOME is a bind mount from app storage, so it hides the rootfs's own /root.
if [ ! -d "$DSH_HOME/.dsh/profiles/web" ] && [ -d "$DSH_INSTALL/dsh-home-seed" ]; then
  echo "start-dsh: seeding $DSH_HOME/.dsh from payload"
  cp -a "$DSH_INSTALL/dsh-home-seed/." "$DSH_HOME/.dsh/"
fi

# The plugin is app code, not user data: refresh it on every start so an app
# update actually ships (the home itself is only seeded once, to keep sessions,
# credentials and user edits). A user who disabled the row keeps it disabled —
# that lives in cordis.patch.yml, which we never rewrite.
# Older builds ran with PRoot's --link2symlink, which left .l2s.* stand-ins for
# hard links in the harness home. They are pure artifacts, and a dangling one
# reads as a corrupt file, so clear them at startup.
rm -f "$DSH_HOME"/.l2s.* 2>/dev/null || true
find "$DSH_HOME" -maxdepth 3 -name '.l2s.*' -delete 2>/dev/null || true

# Refresh the plugin the profile resolves. The app writes this same path
# directly from the hot overlay; this copy covers the case where the guest
# boots without the app having run (fresh profile, manual start).
if [ -d "$DSH_INSTALL/dsh-plugin-android" ] && [ -d "$DSH_HOME/.dsh/profiles/web" ]; then
  target="$DSH_HOME/.dsh/profiles/web/node_modules/dsh-plugin-android"
  if [ ! -d "$target" ]; then
    mkdir -p "$(dirname "$target")"
    cp -a "$DSH_INSTALL/dsh-plugin-android" "$target"
  fi
fi

if [ -n "${DSH_PTY_TOKEN:-}" ]; then
  echo "start-dsh: pty endpoint on 127.0.0.1:$DSH_PTY_PORT"
  DSH_PTY_PORT="$DSH_PTY_PORT" \
  DSH_PTY_TOKEN="$DSH_PTY_TOKEN" \
  DSH_PTY_SHELL="${DSH_PTY_SHELL:-/bin/bash}" \
  "$NODE" "$DSH_INSTALL/android/pty-server.mjs" >>"$DSH_HOME/.dsh-pty.log" 2>&1 &
else
  echo "start-dsh: DSH_PTY_TOKEN unset, terminal disabled"
fi

if ! cd "$DSH_INSTALL" 2>/dev/null; then
  echo "start-dsh: cannot enter $DSH_INSTALL"
  echo "start-dsh: ls -la /opt:"
  ls -la /opt 2>&1 | head -20
  echo "start-dsh: ls -la $DSH_INSTALL:"
  ls -la "$DSH_INSTALL" 2>&1 | head -20
  exit 3
fi
exec "$NODE" --expose-internals \
  "$DSH_INSTALL/node_modules/@deepseek-ai/dsh/lib/bin.js" web \
  --no-open --host 127.0.0.1 --port "$DSH_PORT" \
  --trusted-host "127.0.0.1:$DSH_PORT"
