#!/bin/sh
# Build the DSH Android APK without Gradle.
#
# Pipeline: aapt2 compile+link (resources/manifest) -> javac -> d8 -> hand-rolled
# zip packing (alignment for resources.arsc and .so) -> apksig v2+v3.
# Everything here runs in the Linux build sandbox; aapt2 is an x86_64 glibc binary
# executed through qemu with the staged Debian loader prefix.
set -eu

# The tree this script lives in, so a clone builds wherever it is checked out.
# Override with DSH_SRC_DIR when driving it from a separate build directory.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_VERSION="${APP_VERSION:-$(cat "$ROOT/VERSION" 2>/dev/null || echo 1.0.0)}"
APP="$ROOT/app"
BUILD="$ROOT/build"
OUT="$ROOT/out"
ANDROID_JAR=/tmp/platform/android-36/android.jar
AAPT2=/tmp/aapt2dir/aapt2
D8=/tmp/r8.jar
APKSIG=/tmp/apksig.jar
PROOT=/var/minis/mounts/Download/libproot.so

SRC_JAVA="$APP/java"
LIBS="$APP/libs"
DEX_DIR="$BUILD/dex"
CLASSES="$BUILD/classes"
RES_FLAT="$BUILD/res-flat"
KEYSTORE="$ROOT/keystore/dsh.p12"
KS_PASS="${KS_PASS:-dshandroid}"   # override when building your own release
KS_ALIAS=dsh

mkdir -p "$OUT" "$BUILD" "$DEX_DIR" "$CLASSES/shizuku" "$RES_FLAT"

echo "== 0/7 icons =="
command -v rsvg-convert >/dev/null || { echo "need rsvg-convert (librsvg) for the icon" >&2; exit 1; }
python3 "$ROOT/scripts/render_icon.py"

echo "== 1/7 resources =="
QEMU_LD_PREFIX=/opt/android/root64 qemu-x86_64 "$AAPT2" compile --dir "$APP/res" -o "$RES_FLAT/res.zip"

echo "== 2/7 link =="
rm -rf "$BUILD/r" && mkdir -p "$BUILD/r"
QEMU_LD_PREFIX=/opt/android/root64 qemu-x86_64 "$AAPT2" link \
  -I "$ANDROID_JAR" \
  --manifest "$APP/AndroidManifest.xml" \
  --min-sdk-version 26 --target-sdk-version 28 \
  --version-code "$(echo "$APP_VERSION" | awk -F. '{printf "%d", $1*10000 + $2*100 + $3}')" \
  --version-name "$APP_VERSION" \
  --java "$BUILD/r" \
  -o "$BUILD/base.apk" \
  "$RES_FLAT/res.zip"

echo "== hot overlay =="
python3 "$ROOT/scripts/make_hot_zip.py" "$ROOT" "$BUILD/hot-assets/hot.zip"

echo "== update manifest =="
python3 "$ROOT/scripts/make_update_manifest.py" "$ROOT"

echo "== 3/7 javac =="
python3 - "$BUILD/payload-assets/payload.zip" "$SRC_JAVA/dev/dsh/android/BuildInfo.java" "$APP_VERSION" <<'GEN'
import hashlib, pathlib, sys
archive = pathlib.Path(sys.argv[1])
digest = hashlib.sha256(archive.read_bytes()).hexdigest()[:16]
version = sys.argv[3].strip()   # version string, not a path
code = 0
for part in version.split(".")[:3]:
    code = code * 100 + int(part)
target = pathlib.Path(sys.argv[2])
target.write_text(
    "package dev.dsh.android;\n\n"
    "/** Generated by scripts/build_apk.sh — payload content hash. Do not edit. */\n"
    "final class BuildInfo {\n"
    f'    static final String PAYLOAD_VERSION = "{digest}";\n'
    f'    static final String APP_VERSION = "{version}";\n'
    f"    static final int APP_VERSION_CODE = {code};\n"
    "}\n",
    encoding="utf-8",
)
print(f"   app {version}, payload hash {digest}")
GEN
find "$SRC_JAVA" -name '*.java' > "$BUILD/sources.txt"
# aapt2 --java wrote R.java in step 2; javac must compile it too, and the append
# has to come after the redirect that creates the list.
if [ -d "$BUILD/r" ]; then
  find "$BUILD/r" -name '*.java' >> "$BUILD/sources.txt"
fi
javac -encoding UTF-8 -source 8 -target 8 -nowarn \
  -classpath "$ANDROID_JAR:$(ls "$LIBS"/*.jar | tr '\n' ':')" \
  -d "$CLASSES" @"$BUILD/sources.txt"

echo "== 4/7 d8 =="
mkdir -p "$DEX_DIR"
java -cp "$D8" com.android.tools.r8.D8 --release --min-api 26 \
  --lib "$ANDROID_JAR" \
  --output "$DEX_DIR" \
  $(find "$CLASSES" -name '*.class') "$LIBS"/*.jar

echo "== 5/7 pack =="
python3 "$ROOT/scripts/pack_apk.py" "$BUILD/base.apk" "$BUILD/unsigned.apk" \
  "classes.dex:$DEX_DIR/classes.dex" \
  "lib/arm64-v8a/libproot.so:$PROOT" \
  "assets/payload.zip:$BUILD/payload-assets/payload.zip" \
  "assets/payload.manifest:$BUILD/payload-assets/payload.manifest" \
  "assets/hot.zip:$BUILD/hot-assets/hot.zip"

echo "== 6/7 keystore =="
if [ ! -f "$KEYSTORE" ]; then
  mkdir -p "$(dirname "$KEYSTORE")"
  keytool -genkeypair -keystore "$KEYSTORE" -storetype PKCS12 \
    -storepass "$KS_PASS" -keypass "$KS_PASS" -alias "$KS_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=DSH Android, OU=minis, O=minis, L=, S=, C=CN" >/dev/null 2>&1
  echo "   generated $KEYSTORE"
fi

echo "== 7/7 sign =="
javac -encoding UTF-8 -nowarn -classpath "$APKSIG" -d "$BUILD/sign" "$ROOT/scripts/Sign.java"
java -cp "$APKSIG:$BUILD/sign" Sign \
  "$BUILD/unsigned.apk" "$OUT/dsh-android.apk" "$KEYSTORE" "$KS_PASS" "$KS_ALIAS" "$KS_PASS"

ls -la "$OUT/dsh-android.apk"
